### ISSUE TITLE
管理帳密

### ISSUE THREAD

**Issue by timtan** [PyText2Speech/PyText2Speech#8]
另外有 class 做帳密的讀取，然後再把 class 都給產生出來。

**Comment by chairco** [comment]
增加一個 config.py 用來管理帳號密碼，結構是用一個 server 的 dict 來存。

**Comment by timtan** [comment]
最後裡面的內容，以 yaml 的形式放在  home 目錄讀取如何。

**Comment by chairco** [comment]
改成讀取 家目錄底下的 pytext2speech.json, 如果沒有會建立，如果有但帳號空白會提示錯誤。
